import {
  ArrowRight,
  Award,
  Bell,
  Bike,
  CalendarDays,
  Camera,
  Carrot,
  CheckCircle2,
  ChevronRight,
  CircleHelp,
  Clock3,
  Compass,
  Dumbbell,
  ExternalLink,
  Eye,
  Flag,
  Footprints,
  Gauge,
  Gift,
  HeartHandshake,
  HeartPulse,
  Home,
  Info,
  Landmark,
  Leaf,
  Mail,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  Mountain,
  MountainSnow,
  Newspaper,
  Phone,
  Play,
  Plus,
  Rocket,
  Route,
  RulerDimensionLine,
  Search,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Target,
  Ticket,
  Trophy,
  Users,
  Waves,
  X,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const navLucideIconOptions = [
  { label: 'Alerte', value: 'bell' },
  { label: 'Appel', value: 'phone' },
  { label: 'Boussole', value: 'compass' },
  { label: 'Boutique', value: 'shopping-bag' },
  { label: 'Calendrier', value: 'calendar-days' },
  { label: 'Camera', value: 'camera' },
  { label: 'Cadeau', value: 'gift' },
  { label: 'Cap', value: 'target' },
  { label: 'Carte', value: 'map-pin' },
  { label: 'Chrono', value: 'clock-3' },
  { label: 'Coach', value: 'dumbbell' },
  { label: 'Communaute', value: 'users' },
  { label: 'Contact', value: 'message-circle' },
  { label: 'Course', value: 'footprints' },
  { label: 'Cyclisme', value: 'bike' },
  { label: 'Direction', value: 'arrow-right' },
  { label: 'Distance', value: 'ruler-dimension-line' },
  { label: 'FAQ', value: 'circle-help' },
  { label: 'Forme', value: 'heart-pulse' },
  { label: 'Idee', value: 'zap' },
  { label: 'Inspiration', value: 'sparkles' },
  { label: 'Infos', value: 'info' },
  { label: 'Inscription', value: 'check-circle-2' },
  { label: 'Lien externe', value: 'external-link' },
  { label: 'Mail', value: 'mail' },
  { label: 'Menu', value: 'menu' },
  { label: 'Montagne', value: 'mountain' },
  { label: 'Montagne enneigee', value: 'mountain-snow' },
  { label: 'Nouveaute', value: 'rocket' },
  { label: 'Objectif', value: 'flag' },
  { label: 'Parcours', value: 'route' },
  { label: 'Partage', value: 'heart-handshake' },
  { label: 'Performance', value: 'gauge' },
  { label: 'Play', value: 'play' },
  { label: 'Plus', value: 'plus' },
  { label: 'Protection', value: 'shield-check' },
  { label: 'Publier', value: 'megaphone' },
  { label: 'Recompense', value: 'award' },
  { label: 'Recherche', value: 'search' },
  { label: 'Suivant', value: 'chevron-right' },
  { label: 'Succes', value: 'trophy' },
  { label: 'Sourire', value: 'smile' },
  { label: 'Sponsor', value: 'landmark' },
  { label: 'Star', value: 'star' },
  { label: 'Terrain', value: 'leaf' },
  { label: 'Ticket', value: 'ticket' },
  { label: 'Voir', value: 'eye' },
  { label: 'Vrac', value: 'carrot' },
  { label: 'Vague', value: 'waves' },
  { label: 'X', value: 'x' },
  { label: 'Accueil', value: 'home' },
  { label: 'Actualites', value: 'newspaper' },
  { label: 'Medaille', value: 'medal' },
] as const

export type NavLucideIconName = (typeof navLucideIconOptions)[number]['value']

export const navLucideIcons: Record<NavLucideIconName, LucideIcon> = {
  'arrow-right': ArrowRight,
  award: Award,
  bell: Bell,
  bike: Bike,
  'calendar-days': CalendarDays,
  camera: Camera,
  carrot: Carrot,
  'check-circle-2': CheckCircle2,
  'chevron-right': ChevronRight,
  'circle-help': CircleHelp,
  'clock-3': Clock3,
  compass: Compass,
  dumbbell: Dumbbell,
  'external-link': ExternalLink,
  eye: Eye,
  flag: Flag,
  footprints: Footprints,
  gauge: Gauge,
  gift: Gift,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  home: Home,
  info: Info,
  landmark: Landmark,
  leaf: Leaf,
  mail: Mail,
  'map-pin': MapPin,
  medal: Medal,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  newspaper: Newspaper,
  phone: Phone,
  play: Play,
  plus: Plus,
  rocket: Rocket,
  route: Route,
  'ruler-dimension-line': RulerDimensionLine,
  search: Search,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  ticket: Ticket,
  trophy: Trophy,
  users: Users,
  waves: Waves,
  x: X,
  zap: Zap,
}

export const navLucideSearchAliases: Partial<Record<NavLucideIconName, string[]>> = {
  'calendar-days': ['evenement', 'agenda', 'date'],
  users: ['equipe', 'team', 'membres'],
  'check-circle-2': ['validation', 'ok', 'confirmer'],
  gauge: ['vitesse', 'performance', 'tempo'],
  mail: ['newsletter', 'email', 'contact'],
}
